### ISSUE TITLE
without setup, not clear how to add all the subfolders to the path

### ISSUE THREAD

**Issue by alexlib** [yosefm/pbi#1]
the pbi shall be add to the Python PATH with the subfolders? I think setup.py could still help, even without Cython build?

**Comment by yosefm** [comment]
Yes, like I said, it's not so polished right now. I'll try to find the time. Anyway, the scripts don't need setup. And I think that the utility module (mixintel/) will be imported ok if you run from the PBI directory.

**Comment by yosefm** [comment]
Added a setup script in 59ce808c83. See if it is better for you. The scripts are still to be run from the code directory, I'm not sure where and how to install them.

**Comment by alexlib** [comment]
Thanks. it does help a bit. Though the installation requirements are much longer :) 
see my branch conda_env https://github.com/alexlib/pbi/tree/conda_env
in response to: https://github.com/yosefm/pbi/blob/master/setup.py#L61

**Comment by alexlib** [comment]
more important is that if we could have a copy of test_cavity or any other test case from the openptv examples repository with the YAML files as you use - e.g. to have a test directory in which both parameters/ and yaml parameters are synchronous and transparent for the new users of pbi.

**Comment by yosefm** [comment]
No need to put in everything but the kitchen sink. Some dependencies are optional.

**Comment by alexlib** [comment]
I think that the new /example is exactly the right move
